// Generated by gencpp from file one/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ONE_MESSAGE_ADDTWOINTS_H
#define ONE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <one/AddTwoIntsRequest.h>
#include <one/AddTwoIntsResponse.h>


namespace one
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace one


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::one::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::one::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::one::AddTwoInts > {
  static const char* value()
  {
    return "one/AddTwoInts";
  }

  static const char* value(const ::one::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::one::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::one::AddTwoInts > 
template<>
struct MD5Sum< ::one::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::one::AddTwoInts >::value();
  }
  static const char* value(const ::one::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::one::AddTwoIntsRequest> should match 
// service_traits::DataType< ::one::AddTwoInts > 
template<>
struct DataType< ::one::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::one::AddTwoInts >::value();
  }
  static const char* value(const ::one::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::one::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::one::AddTwoInts > 
template<>
struct MD5Sum< ::one::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::one::AddTwoInts >::value();
  }
  static const char* value(const ::one::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::one::AddTwoIntsResponse> should match 
// service_traits::DataType< ::one::AddTwoInts > 
template<>
struct DataType< ::one::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::one::AddTwoInts >::value();
  }
  static const char* value(const ::one::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ONE_MESSAGE_ADDTWOINTS_H
