// Generated by gencpp from file one/Z.msg
// DO NOT EDIT!


#ifndef ONE_MESSAGE_Z_H
#define ONE_MESSAGE_Z_H

#include <ros/service_traits.h>


#include <one/ZRequest.h>
#include <one/ZResponse.h>


namespace one
{

struct Z
{

typedef ZRequest Request;
typedef ZResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Z
} // namespace one


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::one::Z > {
  static const char* value()
  {
    return "c9caccfcada3b6a45d8528a23bccaf1a";
  }

  static const char* value(const ::one::Z&) { return value(); }
};

template<>
struct DataType< ::one::Z > {
  static const char* value()
  {
    return "one/Z";
  }

  static const char* value(const ::one::Z&) { return value(); }
};


// service_traits::MD5Sum< ::one::ZRequest> should match 
// service_traits::MD5Sum< ::one::Z > 
template<>
struct MD5Sum< ::one::ZRequest>
{
  static const char* value()
  {
    return MD5Sum< ::one::Z >::value();
  }
  static const char* value(const ::one::ZRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::one::ZRequest> should match 
// service_traits::DataType< ::one::Z > 
template<>
struct DataType< ::one::ZRequest>
{
  static const char* value()
  {
    return DataType< ::one::Z >::value();
  }
  static const char* value(const ::one::ZRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::one::ZResponse> should match 
// service_traits::MD5Sum< ::one::Z > 
template<>
struct MD5Sum< ::one::ZResponse>
{
  static const char* value()
  {
    return MD5Sum< ::one::Z >::value();
  }
  static const char* value(const ::one::ZResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::one::ZResponse> should match 
// service_traits::DataType< ::one::Z > 
template<>
struct DataType< ::one::ZResponse>
{
  static const char* value()
  {
    return DataType< ::one::Z >::value();
  }
  static const char* value(const ::one::ZResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ONE_MESSAGE_Z_H
