// Generated by gencpp from file one/z.msg
// DO NOT EDIT!


#ifndef ONE_MESSAGE_Z_H
#define ONE_MESSAGE_Z_H

#include <ros/service_traits.h>


#include <one/zRequest.h>
#include <one/zResponse.h>


namespace one
{

struct z
{

typedef zRequest Request;
typedef zResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct z
} // namespace one


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::one::z > {
  static const char* value()
  {
    return "c9caccfcada3b6a45d8528a23bccaf1a";
  }

  static const char* value(const ::one::z&) { return value(); }
};

template<>
struct DataType< ::one::z > {
  static const char* value()
  {
    return "one/z";
  }

  static const char* value(const ::one::z&) { return value(); }
};


// service_traits::MD5Sum< ::one::zRequest> should match 
// service_traits::MD5Sum< ::one::z > 
template<>
struct MD5Sum< ::one::zRequest>
{
  static const char* value()
  {
    return MD5Sum< ::one::z >::value();
  }
  static const char* value(const ::one::zRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::one::zRequest> should match 
// service_traits::DataType< ::one::z > 
template<>
struct DataType< ::one::zRequest>
{
  static const char* value()
  {
    return DataType< ::one::z >::value();
  }
  static const char* value(const ::one::zRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::one::zResponse> should match 
// service_traits::MD5Sum< ::one::z > 
template<>
struct MD5Sum< ::one::zResponse>
{
  static const char* value()
  {
    return MD5Sum< ::one::z >::value();
  }
  static const char* value(const ::one::zResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::one::zResponse> should match 
// service_traits::DataType< ::one::z > 
template<>
struct DataType< ::one::zResponse>
{
  static const char* value()
  {
    return DataType< ::one::z >::value();
  }
  static const char* value(const ::one::zResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ONE_MESSAGE_Z_H
